
LIB=../../../lib

VHDL_FILES =\
	$(LIB)/math/src/math_pkg.vhd\
	$(LIB)/tb_util/src/tb_util_pkg.vhd\
	$(LIB)/sync/src/sync_pkg.vhd\
	$(LIB)/sync/src/sync.vhd\
	$(LIB)/mem/src/mem_pkg.vhd\
	$(LIB)/mem/src/dp_ram_1c1r1w_rdw.vhd\
	$(LIB)/mem/src/dp_ram_1c1r1w.vhd\
	$(LIB)/mem/src/dp_ram_2c2rw_byteen.vhd\
	$(LIB)/mem/src/dp_ram_2c2rw.vhd\
	$(LIB)/mem/src/fifo_1c1r1w_fwft.vhd\
	$(LIB)/mem/src/fifo_1c1r1w.vhd\
	$(LIB)/sram_ctrl/src/sram_ctrl_pkg.vhd\
	$(LIB)/sram_ctrl/src/sram_ctrl.vhd\
	$(LIB)/sram_ctrl/src/sram_ctrl_arch_ref.vhd\
	$(LIB)/vga_ctrl/src/vga_ctrl_pkg.vhd\
	$(LIB)/vga_ctrl/src/vga_ctrl.vhd\
	$(LIB)/vga_ctrl/src/tpg.vhd\
	$(LIB)/gfx_core/src/gfx_core_pkg.vhd\
	$(LIB)/vga_gfx_ctrl/src/gfx_util_pkg.vhd\
	$(LIB)/vga_gfx_ctrl/src/pixel_writer.vhd\
	$(LIB)/vga_gfx_ctrl/src/pixel_reader.vhd\
	$(LIB)/vga_gfx_ctrl/src/gfx_circle.vhd\
	$(LIB)/vga_gfx_ctrl/src/rasterizer.vhd\
	$(LIB)/vga_gfx_ctrl/src/rasterizer_arch_ref.vhd\
	$(LIB)/vga_gfx_ctrl/src/vga_gfx_ctrl_pkg.vhd\
	$(LIB)/vga_gfx_ctrl/src/frame_reader.vhd\
	$(LIB)/vga_gfx_ctrl/src/vga_gfx_ctrl.vhd\
	$(LIB)/top/src/top.vhd\
	src/rasterizer_arch.vhd\
	tb/rasterizer_tb.vhd


TB=rasterizer_tb



include ../../../util/simple_flow.mk
include ../../../util/quartus.mk

