VHDL_FILES = \
	../sync/src/*.vhd\
	../math/src/*.vhd\
	../mem/src/mem_pkg.vhd\
	../mem/src/dp_ram_1c1r1w.vhd\
	../mem/src/dp_ram_2c2rw.vhd\
	../mem/src/dp_ram_2c2rw_byteen.vhd\
	../mem/src/fifo_1c1r1w.vhd\
	../mem/src/fifo_1c1r1w_fwft.vhd\
	../rv_core/src/rv_core_pkg.vhd\
	../tb_util/src/tb_util_pkg.vhd\
	src/rv_sys_pkg.vhd\
	src/delay.vhd\
	src/virtual_jtag_wrapper.vhd\
	src/memory_jtag.vhd\
	src/memory_sim.vhd\
	src/mm_serial_port.vhd\
	src/mm_counter.vhd\
	src/mm_gpio.vhd\
	src/rv_sys.vhd\
	src/memu.vhd


include ../../util/simple_flow.mk

