
LIB=..

VHDL_FILES = \
	$(LIB)/math/src/math_pkg.vhd\
	$(LIB)/gfx_core/src/gfx_core_pkg.vhd\
	src/tetris_util_pkg.vhd\
	src/tetromino_collider.vhd\
	src/tetromino_drawer.vhd

include ../../util/simple_flow.mk

