
LIB=..

VHDL_FILES = \
	$(LIB)/math/src/math_pkg.vhd\
	$(LIB)/sync/src/sync_pkg.vhd\
	$(LIB)/mem/src/mem_pkg.vhd\
	$(LIB)/sync/src/sync.vhd\
	$(LIB)/sram_ctrl/src/sram_ctrl_pkg.vhd\
	$(LIB)/sram_ctrl/src/sram_ctrl.vhd\
	$(LIB)/sram_ctrl/src/sram_ctrl_arch_ref.vhd\
	$(LIB)/vga_ctrl/src/vga_ctrl_pkg.vhd\
	$(LIB)/vga_ctrl/src/vga_ctrl.vhd\
	$(LIB)/vga_ctrl/src/vga_ctrl_arch_ref.vhd\
	$(LIB)/vga_ctrl/src/tpg.vhd\
	$(LIB)/gfx_core/src/gfx_core_pkg.vhd\
	src/gfx_util_pkg.vhd\
	src/pixel_writer.vhd\
	src/pixel_reader.vhd\
	src/gfx_circle.vhd\
	src/rasterizer.vhd\
	src/rasterizer_arch_ref.vhd\
	src/vga_gfx_ctrl_pkg.vhd\
	src/frame_reader.vhd\
	src/vga_gfx_ctrl.vhd
	
TB=

include ../../util/simple_flow.mk

