LIB=../../../lib

VHDL_FILES =\
	$(LIB)/math/src/math_pkg.vhd\
	$(LIB)/tb_util/src/tb_util_pkg.vhd\
	$(LIB)/gfx_core/src/gfx_core_pkg.vhd\
	src/gfx_cmd_interpreter.vhd\
	tb/gfx_cmd_interpreter_tb.vhd

TB=gfx_cmd_interpreter_tb

include ../../../util/simple_flow.mk



