VHDL_FILES =\
	../../../lib/math/src/math_pkg.vhd\
	../../../lib/util/src/util_pkg.vhd\
	../../../lib/sync/src/sync_pkg.vhd\
	../../../lib/sync/src/sync.vhd\
	../../../lib/tb_util/src/tb_util_pkg.vhd\
	../../../lib/snes_ctrl/src/snes_ctrl_pkg.vhd\
	../../../lib/snes_ctrl/src/snes_ctrl.vhd\
	../../../lib/snes_ctrl/src/snes_ctrl_arch_ref.vhd\
	src/snes_ctrl_arch.vhd\
	tb/snes_ctrl_tb.vhd\
	../../../lib/top/src/top.vhd\
	top_arch.vhd

TB=snes_ctrl_tb
WAVE_FILE=wave.do
GTK_WAVE_FILE=wave.gtkw


include ../../../util/simple_flow.mk

include ../../../util/quartus.mk

