VHDL_FILES =\
	../../../lib/math/src/math_pkg.vhd\
	../../../lib/util/src/util_pkg.vhd\
	../../../lib/tb_util/src/tb_util_pkg.vhd\
	../../../lib/mem/src/mem_pkg.vhd\
	../../../lib/mem/src/dp_ram_1c1r1w.vhd\
	../../../lib/mem/src/fifo_1c1r1w.vhd\
	../../../lib/sram_ctrl/src/sram_ctrl_pkg.vhd\
	../../../lib/sram_ctrl/src/IS61WV102416BLL.vhd\
	../../../lib/sram_ctrl/src/sram_ctrl.vhd\
	../../../lib/sram_ctrl/src/sram_ctrl_arch_ref.vhd\
	../../../lib/top/src/top.vhd\
	src/sram_ctrl_arch.vhd\
	tb/sram_ctrl_tb.vhd\
	top_arch.vhd

TB=sram_ctrl_tb
WAVE_FILE=wave.do
GTK_WAVE_FILE=wave.gtkw


include ../../../util/simple_flow.mk

include ../../../util/quartus.mk

