VHDL_FILES = \
	../../../lib/math/src/math_pkg.vhd\
	../../../lib/sync/src/sync_pkg.vhd\
	../../../lib/sync/src/sync.vhd\
	../../../lib/tb_util/src/tb_util_pkg.vhd\
	../../../lib/mem/src/mem_pkg.vhd\
	../../../lib/mem/src/dp_ram_1c1r1w.vhd\
	../../../lib/mem/src/fifo_1c1r1w.vhd\
	../../../lib/mem/src/fifo_1c1r1w_fwft.vhd\
	../../../lib/mem/src/dp_ram_2c2rw.vhd\
	../../../lib/mem/src/dp_ram_2c2rw_byteen.vhd\
	../../../lib/rv_core/src/rv_core_pkg.vhd\
	../../../lib/rv_sys/src/rv_sys_pkg.vhd\
	../../../lib/rv_sys/src/delay.vhd\
	../../../lib/rv_sys/src/sld_virtual_jtag_stub.vhd\
	../../../lib/rv_sys/src/virtual_jtag_wrapper.vhd\
	../../../lib/rv_sys/src/memory_sim.vhd\
	../../../lib/rv_sys/src/memory_jtag.vhd\
	../../../lib/rv_sys/src/mm_serial_port.vhd\
	../../../lib/rv_sys/src/mm_counter.vhd\
	../../../lib/rv_sys/src/mm_gpio.vhd\
	../../../lib/rv_sys/src/rv_sys.vhd\
	src/rv_sim.vhd\
	tb/rv_sim_tb.vhd

TB=rv_sim_tb
WAVE_FILE=wave.do
GTK_WAVE_FILE=wave.gtkw

include ../../../util/simple_flow.mk

