VHDL_FILES =\
	../../../lib/math/src/math_pkg.vhd\
	../../../lib/util/src/util_pkg.vhd\
	../../../lib/sync/src/sync_pkg.vhd\
	../../../lib/sync/src/sync.vhd\
	../../../lib/tb_util/src/tb_util_pkg.vhd\
	../../../lib/gc_ctrl/src/gc_ctrl_pkg.vhd\
	../../../lib/gc_ctrl/src/gc_ctrl.vhd\
	../../../lib/top/src/top.vhd\
	src/gc_ctrl_arch.vhd\
	tb/gc_ctrl_tb.vhd\
	top_arch.vhd


TB=gc_ctrl_tb
WAVE_FILE=wave.do
GTK_WAVE_FILE=wave.gtkw


include ../../../util/simple_flow.mk

include ../../../util/quartus.mk

