VHDL_FILES =\
	../../../lib/math/src/math_pkg.vhd\
	../../../lib/util/src/util_pkg.vhd\
	../../../lib/tb_util/src/tb_util_pkg.vhd\
	../../../lib/vga_ctrl/src/vga_ctrl_pkg.vhd\
	../../../lib/vga_ctrl/src/tpg.vhd\
	../../../lib/vga_ctrl/src/dac_dump.vhd\
	../../../lib/vga_ctrl/src/vga_ctrl.vhd\
	../../../lib/vga_ctrl/src/vga_ctrl_arch_ref.vhd\
	../../../lib/top/src/top.vhd\
	src/vga_ctrl_arch.vhd\
	src/pll.vhd\
	tb/vga_ctrl_tb.vhd\
	top_arch.vhd

TB=vga_ctrl_tb
WAVE_FILE=wave.do
GTK_WAVE_FILE=wave.gtkw

CLEAN_FILES=*.bmp
CLEAN_DIRS=vendor_libs
GHDL_USE_ALTERA_LIB=1


include ../../../util/simple_flow.mk

include ../../../util/quartus.mk

