VHDL_FILES = \
	../math/src/math_pkg.vhd \
	../sync/src/sync_pkg.vhd\
	../sync/src/sync.vhd\
	../mem/src/mem_pkg.vhd \
	../mem/src/dp_ram_1c1r1w.vhd \
	../mem/src/fifo_1c1r1w.vhd \
	../mem/src/fifo_1c1r1w_fwft.vhd \
	src/uart_data_streamer_pkg.vhd \
	src/uart_data_streamer.vhd


include ../../util/simple_flow.mk
