VHDL_FILES = \
	../math/src/math_pkg.vhd\
	../mem/src/mem_pkg.vhd\
	../mem/src/dp_ram_1c1r1w.vhd\
	../mem/src/fifo_1c1r1w.vhd\
	../mem/src/fifo_1c1r1w_fwft.vhd\
	./src/sram_ctrl_pkg.vhd\
	./src/sram_ctrl.vhd\
	./src/IS61WV102416BLL.vhd\
	./src/sram_ctrl_arch_ref.vhd


include ../../util/simple_flow.mk
